bootstrap.d/0/*: handle only the sources we provided

diff --git a/bootstrap.d/0/06-gcc b/bootstrap.d/0/06-gcc
--- a/bootstrap.d/0/06-gcc
+++ b/bootstrap.d/0/06-gcc
@@ -1,6 +1,6 @@
 # Build script for gcc (final)
 #
-# Copyright (C) 2014 Matias A. Fonzo.
+# Copyright (C) 2014, 2015 Matias A. Fonzo.
 #
 # This script is free software: you have unlimited permission
 # to copy, distribute and modify it.
@@ -9,7 +9,7 @@ version=4.9.2
 
 echo "Unpacking gcc-${version} ..."
 rm -rf "${tmpdir}"/gcc-${version}
-tar xf "${tardir}"/gcc-${version}.tar.?z* -C "$tmpdir"
+tar xf "${tardir}"/gcc-${version}.tar.lz -C "$tmpdir"
 
 # Build instructions
 cd "${tmpdir}"/gcc-${version}
@@ -18,11 +18,11 @@ patch -Np0 -i "${patchdir}"/gcc/gcc-nofixincludes
 patch -Np1 -i "${patchdir}"/gcc/gcc-4.9.0-musl.diff
 
 # Build GCC built-in prerequisites
-for file in "${tardir}"/gmp-* "${tardir}"/mpfr-* "${tardir}"/mpc-* ; do
+for file in "${tardir}"/gmp-*.tar.lz "${tardir}"/mpfr-*.tar.lz "${tardir}"/mpc-*.tar.lz ; do
   if [ ! -e "$file" ] ; then
-    echo "The built-in prerequisite \`${file}' for GCC is required." 1>&2
+    echo "The built-in prerequisite \`${file##*/}' for GCC is required." 1>&2
     exit 1
-  fi  
+  fi
 
   # Unpack prerequisite
   tar xf "$file"
