bootstrap: new version
Changes in this version:

- LDFLAGS_BINUTILS has been renamed to LDFLAGS_LIBTOOL,
  and is no longer an environment variable.

- The "stage.d" directory has been renamed to "stage".

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -114,7 +114,7 @@ VENDOR="${VENDOR:-dragora}"
 CFLAGS="${CFLAGS:--Os}"
 CXXFLAGS="${CXXFLAGS:-$CFLAGS}"
 LDFLAGS="${LDFLAGS:--static}"
-LDFLAGS_BINUTILS="${LDFLAGS_BINUTILS:---static}"
+LDFLAGS_LIBTOOL=--static
 
 # Parse options
 while getopts ":hSVk a:c:j:r:s:t:" option ; do
@@ -147,7 +147,7 @@ while getopts ":hSVk a:c:j:r:s:t:" option ; do
       ;;
     V)
       printf '%s\n' \
-       "bootstrap 2.4" \
+       "bootstrap 2.5" \
        "Copyright (C) 2014, 2015, 2016  Matias A. Fonzo." \
        "License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>" \
        "This is free software: you are free to change and redistribute it." \
@@ -279,17 +279,17 @@ umask 022
 mkdir -p "${tmpdir}/sources" "$crossdir" "$rootdir"
 
 # Process the files from stage number
-for file in ""${CWD}/stage.d/${stage}/${@:-??-*}"" ; do
+for file in ""${CWD}/stage/${stage}/${@:-??-*}"" ; do
 
   # Get the basename
   file="${file##*/}"
 
-  if [ ! -f "${CWD}/stage.d/${stage}/$file" ] ; then
-    echo "bootstrap: File '${CWD}/stage.d/${stage}/$file' not found or not regular." 1>&2
+  if [ ! -f "${CWD}/stage/${stage}/$file" ] ; then
+    echo "bootstrap: File '${CWD}/stage/${stage}/$file' not found or not regular." 1>&2
     exit 1
   fi
 
-  if [ ! -x "${CWD}/stage.d/${stage}/$file" ] ; then
+  if [ ! -x "${CWD}/stage/${stage}/$file" ] ; then
     echo "bootstrap: I won't build '${stage}/$file'.  File not executable." 1>&2
     continue;
   fi
@@ -312,7 +312,7 @@ for file in ""${CWD}/stage.d/${stage}/${@:-??-*}"" ; do
 
   # Load script
   echo "==> File \"${file##*/}\" from stage $stage in progress ..."
-  . "${CWD}/stage.d/${stage}/$file"
+  . "${CWD}/stage/${stage}/$file"
 
   # Back to the current working directory
   if ! cd "$CWD" 2> /dev/null ; then
